name: Xcode Unit Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-ios:
    runs-on: macos-11.0

    steps:
    - uses: actions/checkout@v2

    - name: Linter
      run: swiftlint

    - name: Select Xcode
      run: sudo xcode-select -s "/Applications/Xcode_12.3.app"

    - name: Xcode version
      run: /usr/bin/xcodebuild -version

    - name: Create iPhone SE Simulator
      run: xcrun simctl create "iPhone SE (1st generation)" "iPhone SE (1st generation)"

    - name: Xcode test on iPhone SE
      run: xcodebuild clean test -scheme RenaudJennyAboutView-Package -destination 'platform=iOS Simulator,name=iPhone SE (1st generation)'

    - uses: actions/upload-artifact@v2
      if: failure()
      with:
        name: failed-screenshots
        path: '~/Library/Developer/CoreSimulator/Devices/*/data/Containers/Data/Application/*/tmp/*'
        retention-days: 5

  build-macos:
    runs-on: macos-11.0

    steps:
    - uses: actions/checkout@v2

    - name: List all available build targets and schemes
      run: xcodebuild -list

    - name: Xcode test on Mac
      run: xcodebuild clean test -scheme RenaudJennyAboutView-Package -destination 'platform=OS X'
